# Generated by Django 3.2 on 2021-04-18 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApacheLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(db_index=True, max_length=50, verbose_name='ip адрес')),
                ('request_date', models.DateTimeField(verbose_name='дата и время запроса')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('HEAD', 'HEAD'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('TRACE', 'TRACE'), ('CONNECT', 'CONNECT')], db_index=True, max_length=7, verbose_name='метод')),
                ('uri', models.TextField(verbose_name='запрос')),
                ('response_size', models.PositiveIntegerField(verbose_name='размер ответа')),
                ('response_code', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(526)], verbose_name='код ответа')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
